### ISSUE TITLE
get_entry_points: Use after free.

### ISSUE THREAD

**Issue by cheako** [grovesNL/spirv_cross#118]
https://github.com/grovesNL/spirv_cross/blob/231566943b9661008c7a17a6afd388323cbdbfc7/spirv_cross/src/compiler.rs#L265-L267

The array is allocated as one whole, but each element of the array is freed individually.  As the first element is freed first the other accesses are then working on un-allocated memory.

Also ```void free(void*)```, by definition, cannot return anything and thus never fails, but you are attempting to handle cases where it does.

**Comment by grovesNL** [comment]
Yes I think you're right. IIRC this was changed slightly when support was added for the wasm backend. I guess we haven't hit this issue yet because most shaders only have a single entry point.

`check!` just catches all exceptions, so it should be fine if `sc_internal_free_pointer` will never actually throw anything.

**Comment by cheako** [comment]
check! has the side effect of making functions that can never return with failure be prototyped as if they can.  I could see a case for wanting the future proof the API, but I think that's ill advised.

**Comment by grovesNL** [comment]
Right, but the issue is that exceptions can be thrown by almost anywhere we interact with SPIRV-Cross, and unwinding across the Rust/C++ boundary is undefined behavior (i.e. see `catch_unwind`). So even if `check!` isn't needed for `free` here, some other call in the same function body might require it anyway, so the `Result` in the API is still necessary.

Although I think we're going to move to using assertions instead of exceptions anyway, through use of the assertions flag in SPIRV-Cross (some other codebases which use spirv_cross require C++ exceptions be disabled). This isn't great for making errors recoverable, but we could probably later split this into checked/unchecked variants later (where the checked variants could do some simple checking like validating IDs and still return `Result`).

**Comment by cheako** [comment]
I'd PM instead of cluttering the issue, but github sigh.

I don't understand C++.  I managed to add support for get_active_buffer_ranges() without any consideration for exceptions, didn't even realize they were part of C++ until now.
