### ISSUE TITLE
Update to more recent upstream?

### ISSUE THREAD

**Issue by mkeeter** [grovesNL/spirv_cross#165]
I recently ran into [this issue](https://github.com/KhronosGroup/SPIRV-Cross/pull/1594) when writing code using `wgpu-native`.

Any interest in updating the `spirv_cross` crate to the most recent upstream?  I'm happy to test whether a simple submodule bump works, or whether more of the API has changed.

Pushing the fix all the way downstream to `wgpu-native` is going to be a challenge, as I think it goes through
- `spirv_cross`
- `gfx` backends
- `gfx-hal` proper
- `wgpu-core`
- `wgpu-native`

But having an updated `spirv_cross` is the first step!

**Comment by grovesNL** [comment]
Sure, no problem. I just published 0.23 because there were some small breaking changes since the last release. We could've managed a patch release for spirv_cross, but it's useful to get the breaking changes into gfx anyway.

We currently pin wgpu-core's `master` branch to git commits of gfx and regularly update it, so we can probably propagate this to wgpu-native's `master` branch pretty quickly.

**Comment by mkeeter** [comment]
Awesome, thanks!
